name: private_spatial_dk
channels:
  - conda-forge
dependencies:
  - python=3.6.2=0
  - numpy=1.12.1
  - pandas=0.22
  - scipy=0.19.1
  - shapely=1.6.4
  - fiona=1.7.9
  - geopandas=0.3.0
  - seaborn=0.8.1
  - python-igraph=0.7.1
  - louvain=0.6.1
  - ipyparallel=6.0.0
  - nose=1.3.7
  - tqdm
  - pip:
    - tables==3.4.2
                  
